[package]
name = "auth"
version = "0.1.8"
authors = ["Nyx <nnyyxxxx@protonmail.com>"]
license = "GPL-2.0"
description = "Authenticator TUI made in rust, generate totps on the fly. "
repository = "https://github.com/nnyyxxxx/auth.git"
readme = "readme.md"
keywords = [
    "authenticator",
    "tui",
]
edition = "2021"

[dependencies]
ratatui = "0.29.0"
totp-rs = "5.6.0"
anyhow = "1.0.95"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.19"
dirs = "6.0.0"
base32 = "0.5.1"
age = "0.11.1"
secrecy = "0.10.3"
nix = { version = "0.29.0", features = ["user"] }
clap = { version = "4.5.26", features = ["derive"] }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
opt-level = 3
