[package]
name = "auth"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.5", package = "gtk4" }
totp-rs = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
glib = "0.16"
futures = "0.3"
