name: Typos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  typos:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for typos
        uses: crate-ci/typos@v1.29.9
        with:
          config: ./.github/typos.toml